name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          days-before-stale: 90
          days-before-close: 7

          stale-issue-message: >
            This issue is stale because it has been open for 90 days with no activity.
            Please comment or it will be closed in 7 days.
          stale-pr-message: >
            This PR is stale because it has been open for 90 days with no activity.
            Please comment or it will be closed in 7 days.

          close-issue-message: >
            This issue was closed because it remained inactive for 7 days after being marked stale.
          close-pr-message: >
            This PR was closed because it remained inactive for 7 days after being marked stale.

          stale-issue-label: â³ stale
          stale-pr-label: â³ stale

          only-labels: âŒ› awaiting-author
          days-before-stale-issues: 30
          days-before-stale-prs: 30

          stale-issue-message-when-labeled: >
            This issue has been waiting for author feedback for 30 days.
            Please provide the requested information or this issue will be closed in 7 days.
          stale-pr-message-when-labeled: >
            This PR has been waiting for author feedback for 30 days.
            Please provide the requested information or this PR will be closed in 7 days.

          close-issue-message-when-labeled: >
            This issue was closed because the author did not follow up after 7 days.
          close-pr-message-when-labeled: >
            This PR was closed because the author did not follow up after 7 days.

          exempt-issue-labels: â˜ ï¸ wontfix, ğŸ”´ critical
          exempt-pr-labels: â˜ ï¸ wontfix, ğŸ”´ critical
          exempt-all-milestones: true

          remove-stale-when-updated: true
